### PR TITLE
Master

### PR DESCRIPTION
**Pull request by slick-nic**
Added ability to add attachment from byte-array (in memory) rather than loading from filesystem. Added SetTracking to the MessageBuilder object.

### CODE REVIEW

**Comment by bringking** [comment]
Thanks this looks good. I will try and do a release to Nuget ASAP

**Comment by slick-nic** [comment]
Excellent, Thanks.

**Comment by bluebirdtech** [comment]
A NuGet release would be great.  Just bumped into the same need.

**Comment by bringking** [comment]
https://www.nuget.org/packages/mailgun_csharp/0.5.0
https://www.nuget.org/packages/mailgun_csharp.AspNet.Identity/0.6.0

**Comment by bringking** [comment]
@slick-nic or @bluebirdtech I don't actually use this in prod anymore (I switch jobs), so I don't activity maintain this. If you guys would like to take over, I would be happy to make you owners on Nuget and or collaborators on Github (or transfer ownership completely if preferred). Let me know if you would like to take the torch! 🙏

**Comment by bluebirdtech** [comment]
Thanks for updating NuGet so promptly @bringking. I'd love to help, but I'm not your man I'm afraid. No time to give to it and only using Mailgun since today..

**Pull request merged**
