### PR TITLE
Improve quoting for display name, introduce some checks

### LINKED ISSUE #8: Mailgun API update — email RFC checker
From mailgun support:

> we recently made a change that would cause our API to no longer accept messages where the email address does not comply with RFC guidelines. ... We've rolled this back so the "should not work" should actually continue to work. However, we urge that you comply with the RFC guidelines above, as we will eventually be moving forward to comply with them as well.

I'll submit patch this week with full changes, as my fix seems not enough, so you could just assign this issue to me

### PR DESCRIPTION
**Pull request by leotsarev**
fixes #8

### CODE REVIEW

**Comment by bringking** [comment]
@leotsarev Thanks for this! I sent you a link to be a collaborator, since I don't have time to properly test these PR's. Once you are a collaborator, feel free to merge as you see fit.

**Comment by leotsarev** [comment]
Merged. What's plan about NuGet? Do you have some sort of CI?

**Comment by leotsarev** [comment]
@bringking do you have any plans about NuGet ?

**Comment by bringking** [comment]
@leotsarev I don't, but I can add you as an owner to the nuget package, and you can publish new versions. What is your nuget username?

**Comment by leotsarev** [comment]
http://www.nuget.org/profiles/leotsarev

**Comment by bringking** [comment]
@leotsarev okay I added you as an owner!

**Pull request merged**
